---
- name: Deploying simple web app
  hosts: ec2-instance-1
 
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

    - name: Python and its dependencies
      apt: name={{ item }} state=present
      with_items:
        - python3
        - python3-setuptools
        - python3-dev
        - build-essential
        - python3-pip
        - python3-mysqldb
      become: yes

    - name: Install MySQL database
      apt: name={{ item }} state=present
      with_items:
        - mysql-server
        - mysql-client
      become: yes

    - name: Start the database service
      service: 
        name: mysql
        state: started
        enabled: true

    - name: Check if MySQL root login works
      shell: |
        mysql -u root -p'root@123' -e "SELECT 1;" --socket=/var/run/mysqld/mysqld.sock
      register: mysql_root_login_check
      failed_when: false
      changed_when: false
      become: yes

    - name: Set MySQL root password
      mysql_user:
        name: root
        host: localhost
        password: root@123
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present
      when: mysql_root_login_check.rc != 0
      become: yes


    - name: Create a new database with name 'employee_db'
      mysql_db:
        name: employee_db
        state: present
        login_user: root
        login_password: root@123

    - name: Install Flask and dependencies
      pip: 
        name: "{{ item }}"
        executable: pip3
        extra_args: --break-system-packages
        state: present
      with_items:
      - flask
      - flask-mysql
    
    - name: Copy source code to dest server
      copy: src=app.py dest=/opt/app.py
      become: yes
