---
- name: Deploying simple web app
  hosts: ec2
  tasks:
    - name: sleeping
      shell: sleep 30
      async: 65
      poll: 0
      register: sleep_status
    - name: bye bye
      debug: 
        msg: "bye bye"
    - name: check status
      async_status: 
        jid: "{{ sleep_status.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 4
      delay: 10